DROP TABLE IF EXISTS DWLY_HITS;
CREATE TABLE DWLY_HITS(
 	DHID INT PRIMARY KEY AUTO_INCREMENT,  	
  	GITHUB_LINK VARCHAR(250) UNIQUE,
  	HIT_CODE VARCHAR(25),
  	HIT_N_CODE INT,
  	PUBLIC_LINK INT,  	  	
  	
  	ADDED_DATE DATETIME
)  AUTO_INCREMENT = 1000;